force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Basic TV</fullName>
            </value>
            <value>
                <fullName>Smart TV</fullName>
            </value>
            <value>
                <fullName>SmartPhones</fullName>
            </value>
            <value>
                <fullName>Tablets</fullName>
            </value>
            <value>
                <fullName>Kitchen Appliances</fullName>
            </value>
            <value>
                <fullName>Other Appliances</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
                <default>true</default>
                <label>TV</label>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Appliances</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderManagementAppService.cls
public with sharing class OrderManagementAppService {
        
    @AuraEnabled(cacheable=true)
    public static List<Product__c> getProducts(){
        try {
            if(Schema.sObjectType.Product__c.isAccessible()) {
                return [SELECT Id, Name, Description__c, Family__c, Price__c, Type__c, Image__c FROM Product__c LIMIT 10000];
            } else {
                throw new AuraHandledException('You don\'t have access to the Product object');
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String getUrlStringFromServer(String productName){
        try {

            Http httpObject = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('http://www.glyffix.com/api/Image?word=' + productName.escapeHtml4().replace(' ', '%20'));
            request.setHeader('Content-Type', 'application/json');
            request.setHeader('accept','application/json');
            request.setMethod('GET');
            HttpResponse response = httpObject.send(request);
            String responseBody = response.getBody();
            System.debug(responseBody);

            GlyffixWrapper wrapper = (GlyffixWrapper)JSON.deserializeStrict(responseBody, GlyffixWrapper.class);
            System.debug(wrapper);
            
            if (wrapper.rowcount > 0) {
                return wrapper.data[0].imageurl;
            } else {
                return '';
            }
            

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    class GlyffixWrapper {
        boolean success;
        String word;
        Integer rowcount;
        List<glyffixDataWrapper> data; 
        String errormessage;

        GlyffixWrapper(boolean success, String word, Integer rowcount, List<glyffixDataWrapper> data, String errormessage) {
            this.success = success;
            this.word = word;
            this.rowcount = rowcount;
            this.data = data;
            this.errormessage = errormessage;
        }
    }

    class GlyffixDataWrapper {
        String id;
        String imageurl;

        GlyffixDataWrapper(String id, String imageurl) {
            this.id = id;
            this.imageurl = imageurl;
        }
    }
}