force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/TotalProductCount__c.field-meta.xml
<CustomField>
    <fullName>TotalProductCount__c</fullName>
    <label>Total Product Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{0000}</displayFormat>
        <label>Order Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>OrderId</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderItemTriggerHandler.cls
public with sharing class OrderItemTriggerHandler {

    public static void addOrderItem(List<OrderItem__c> orderItems) {
        updateOrderManagementTotalFields(orderItems);
    }

    public static void deleteOrderItem(List<OrderItem__c> orderItems) {
        updateOrderManagementTotalFields(orderItems);
    }

    private static void updateOrderManagementTotalFields(List<OrderItem__c> orderItems) {
        List<Id> orderIdsToUpdate = new List<Id>();

        for (OrderItem__c orderItem : orderItems) {
            orderIdsToUpdate.add(orderItem.OrderId__c);
        }
        
        List<Order__c> ordersToUpdate = [
                SELECT Id, TotalPrice__c, TotalProductCount__c,
                    (SELECT Id, OrderId__c, Quantity__c, Price__c FROM Order_Items__r)
                FROM Order__c
                WHERE Id IN :orderIdsToUpdate
        ];

        for (Order__c each : ordersToUpdate) {
            each.TotalProductCount__c = 0;
            each.TotalPrice__c = 0;
            for (OrderItem__c orderItem : each.Order_Items__r) {
                each.TotalProductCount__c += orderItem.Quantity__c;
                each.TotalPrice__c += orderItem.Price__c;
            }
        }
        
        Database.update(ordersToUpdate);
    }
}